# Generated by Django 5.2.9 on 2025-12-18 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('edited_text', models.TextField()),
                ('section', models.CharField(help_text='Section of report that was edited', max_length=50)),
                ('edit_reason', models.TextField(blank=True, help_text='Reason for edit (optional)')),
                ('character_change_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Edit',
                'verbose_name_plural': 'Report Edits',
                'db_table': 'report_edits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(max_length=500, upload_to='reports/pdfs/')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('include_3d_render', models.BooleanField(default=True)),
                ('include_all_slices', models.BooleanField(default=False)),
                ('selected_slice_ids', models.JSONField(blank=True, help_text='List of Slice2DVisualization IDs to include', null=True)),
                ('version_number', models.IntegerField(default=1)),
                ('watermark', models.CharField(default='DRAFT - FOR RESEARCH PURPOSES ONLY', help_text='Watermark text for the PDF', max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report PDF',
                'verbose_name_plural': 'Report PDFs',
                'db_table': 'report_pdfs',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('brain_tumor', 'Brain Tumor'), ('stroke', 'Stroke/ISLES'), ('alzheimers', "Alzheimer's/OASIS"), ('custom', 'Custom')], max_length=30)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('template_text', models.TextField(help_text='Template with placeholders for AI-generated content')),
                ('required_fields', models.JSONField(help_text='List of required fields in findings_json')),
                ('sections_structure', models.JSONField(help_text='Defines report sections and their order')),
                ('llm_instructions', models.TextField(help_text='Instructions for the LLM on how to populate this template')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'db_table': 'report_templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TraceabilityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_text', models.TextField()),
                ('sentence_index', models.IntegerField(help_text='Position in the report')),
                ('section', models.CharField(max_length=50)),
                ('evidence_path', models.CharField(help_text='JSON path to evidence in findings_json (e.g., "tumor_metrics.whole_tumor_volume")', max_length=255)),
                ('evidence_value', models.JSONField(help_text='The actual value from findings_json')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence in this traceability mapping (0-1)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Traceability Link',
                'verbose_name_plural': 'Traceability Links',
                'db_table': 'traceability_links',
                'ordering': ['report', 'sentence_index'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ai_generated_text', models.TextField(help_text='Original AI-generated narrative')),
                ('finalized_text', models.TextField(help_text='Clinician-edited final text')),
                ('findings_json', models.JSONField(help_text='Structured findings from segmentation')),
                ('traceability_map', models.JSONField(blank=True, help_text='Maps report sentences to evidence in findings_json', null=True)),
                ('template_name', models.CharField(default='standard_brain_tumor', max_length=100)),
                ('template_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('finalized', 'Finalized'), ('exported', 'Exported')], default='draft', max_length=20)),
                ('edit_count', models.IntegerField(default=0, help_text='Number of clinician edits')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_model_name', models.CharField(default='MedAlpaca-7B', max_length=100)),
                ('llm_model_version', models.CharField(blank=True, max_length=50)),
                ('generation_parameters', models.JSONField(blank=True, help_text='LLM generation parameters used', null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='cases.case')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
