# Generated by Django 5.2.9 on 2025-12-18 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContinualLearningTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing_data', 'Preparing Data'), ('training', 'Training'), ('evaluating', 'Evaluating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('new_dataset_name', models.CharField(max_length=200)),
                ('new_dataset_path', models.CharField(max_length=500)),
                ('num_samples', models.IntegerField(default=0)),
                ('use_ewc', models.BooleanField(default=True)),
                ('use_replay', models.BooleanField(default=True)),
                ('ewc_lambda', models.FloatField(default=1000.0)),
                ('replay_buffer_size', models.IntegerField(default=500)),
                ('config', models.JSONField(help_text='Training configuration')),
                ('training_metrics', models.JSONField(blank=True, null=True)),
                ('evaluation_results', models.JSONField(blank=True, null=True)),
                ('learning_accuracy', models.FloatField(blank=True, help_text='Performance on new task', null=True)),
                ('retention_accuracy', models.FloatField(blank=True, help_text='Performance on old tasks', null=True)),
                ('forgetting_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Continual Learning Task',
                'verbose_name_plural': 'Continual Learning Tasks',
                'db_table': 'continual_learning_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('task_type', models.CharField(choices=[('segmentation', 'Segmentation'), ('report_generation', 'Report Generation'), ('visualization', '3D Visualization'), ('pdf_export', 'PDF Export')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='0-100')),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('total_steps', models.IntegerField(default=1)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('device_used', models.CharField(blank=True, help_text='cuda/cpu', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inference Task',
                'verbose_name_plural': 'Inference Tasks',
                'db_table': 'inference_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('model_type', models.CharField(choices=[('segmentation', 'Segmentation Model (MoME+)'), ('llm', 'Language Model')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Model size in bytes')),
                ('checksum', models.CharField(help_text='SHA256 checksum', max_length=64)),
                ('trained_on_task', models.CharField(blank=True, max_length=100)),
                ('training_dataset', models.CharField(blank=True, max_length=200)),
                ('training_date', models.DateTimeField(blank=True, null=True)),
                ('validation_metrics', models.JSONField(blank=True, help_text='Dice scores, IoU, etc.', null=True)),
                ('benchmark_results', models.JSONField(blank=True, null=True)),
                ('forgetting_score', models.FloatField(blank=True, help_text='Backward transfer metric', null=True)),
                ('hyperparameters', models.JSONField(blank=True, null=True)),
                ('architecture_config', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('training', 'Training'), ('testing', 'Testing'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='training', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'db_table': 'model_versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
