# Generated by Django 5.2.9 on 2025-12-18 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('inference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='continuallearningtask',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inferencetask',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_tasks', to='cases.case'),
        ),
        migrations.AddField(
            model_name='inferencetask',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_versions', to='inference.modelversion'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='trained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='continuallearningtask',
            name='base_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_tasks_from_this_model', to='inference.modelversion'),
        ),
        migrations.AddField(
            model_name='continuallearningtask',
            name='new_model_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cl_task', to='inference.modelversion'),
        ),
        migrations.AddIndex(
            model_name='inferencetask',
            index=models.Index(fields=['celery_task_id'], name='inference_t_celery__3da854_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencetask',
            index=models.Index(fields=['status'], name='inference_t_status_fb96c9_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencetask',
            index=models.Index(fields=['task_type'], name='inference_t_task_ty_f960a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelversion',
            unique_together={('name', 'version')},
        ),
    ]
