# Generated by Django 5.2.9 on 2025-12-18 15:50

import cases.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('patient_id', models.CharField(help_text='De-identified patient ID (no PII)', max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], default='created', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('age', models.IntegerField(blank=True, help_text='Patient age at scan', null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('clinical_history', models.TextField(blank=True, help_text='Relevant clinical history')),
                ('indication', models.TextField(blank=True, help_text='Indication for imaging')),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('scanner_type', models.CharField(blank=True, help_text='MRI scanner model', max_length=100)),
                ('field_strength', models.CharField(blank=True, choices=[('1.5T', '1.5 Tesla'), ('3T', '3 Tesla'), ('7T', '7 Tesla')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_ended_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('segmentation_model_version', models.CharField(blank=True, max_length=50)),
                ('llm_model_version', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('is_training_data', models.BooleanField(default=False, help_text='Use for continual learning')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicianFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('segmentation_error', 'Segmentation Error'), ('report_error', 'Report Error'), ('general', 'General Feedback')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('description', models.TextField()),
                ('correction_data', models.JSONField(blank=True, help_text='Corrected segmentation or report data', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinician Feedback',
                'verbose_name_plural': 'Clinician Feedback',
                'db_table': 'clinician_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MRIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('t1', 'T1'), ('t1ce', 'T1 Contrast Enhanced'), ('t2', 'T2'), ('flair', 'FLAIR')], max_length=10)),
                ('file_path', models.FileField(max_length=500, upload_to=cases.models.case_upload_path)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('original_filename', models.CharField(max_length=255)),
                ('dimensions', models.JSONField(blank=True, help_text='Image dimensions [x, y, z]', null=True)),
                ('spacing', models.JSONField(blank=True, help_text='Voxel spacing [x, y, z]', null=True)),
                ('orientation', models.CharField(blank=True, max_length=10)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MRI Image',
                'verbose_name_plural': 'MRI Images',
                'db_table': 'mri_images',
                'ordering': ['case', 'modality'],
            },
        ),
        migrations.CreateModel(
            name='Slice2DVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane', models.CharField(choices=[('axial', 'Axial'), ('coronal', 'Coronal'), ('sagittal', 'Sagittal')], max_length=10)),
                ('slice_index', models.IntegerField(help_text='Slice index in the volume')),
                ('image_file', models.ImageField(max_length=500, upload_to=cases.models.case_upload_path)),
                ('modality', models.CharField(choices=[('t1', 'T1'), ('t1ce', 'T1 Contrast Enhanced'), ('t2', 'T2'), ('flair', 'FLAIR')], max_length=10)),
                ('has_overlay', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '2D Slice Visualization',
                'verbose_name_plural': '2D Slice Visualizations',
                'db_table': 'slice_2d_visualizations',
                'ordering': ['plane', 'slice_index'],
            },
        ),
        migrations.CreateModel(
            name='SegmentationResult',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='segmentation_result', serialize=False, to='cases.case')),
                ('whole_tumor_mask', models.FileField(max_length=500, upload_to=cases.models.case_upload_path)),
                ('tumor_core_mask', models.FileField(max_length=500, upload_to=cases.models.case_upload_path)),
                ('enhancing_tumor_mask', models.FileField(max_length=500, upload_to=cases.models.case_upload_path)),
                ('gltf_file', models.FileField(blank=True, max_length=500, null=True, upload_to=cases.models.case_upload_path)),
                ('whole_tumor_volume', models.FloatField(help_text='WT volume in mm³')),
                ('tumor_core_volume', models.FloatField(help_text='TC volume in mm³')),
                ('enhancing_tumor_volume', models.FloatField(help_text='ET volume in mm³')),
                ('whole_tumor_confidence', models.FloatField(blank=True, null=True)),
                ('tumor_core_confidence', models.FloatField(blank=True, null=True)),
                ('enhancing_tumor_confidence', models.FloatField(blank=True, null=True)),
                ('tumor_location', models.JSONField(blank=True, help_text='Centroid coordinates [x, y, z]', null=True)),
                ('boundary_features', models.JSONField(blank=True, null=True)),
                ('structured_findings', models.JSONField(help_text='Structured JSON for LLM report generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segmentation Result',
                'verbose_name_plural': 'Segmentation Results',
                'db_table': 'segmentation_results',
            },
        ),
    ]
