# Generated by Django 5.2.9 on 2025-12-18 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicianfeedback',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='cases.case'),
        ),
        migrations.AddField(
            model_name='clinicianfeedback',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mriimage',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mri_images', to='cases.case'),
        ),
        migrations.AddField(
            model_name='slice2dvisualization',
            name='segmentation_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slice_visualizations', to='cases.segmentationresult'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['patient_id'], name='cases_patient_a4ce69_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_status_e2ca9e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_by', '-created_at'], name='cases_created_a7158c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mriimage',
            unique_together={('case', 'modality')},
        ),
        migrations.AlterUniqueTogether(
            name='slice2dvisualization',
            unique_together={('segmentation_result', 'plane', 'slice_index', 'modality')},
        ),
    ]
