# Generated by Django 5.2.9 on 2026-03-02 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='patient_user',
            field=models.ForeignKey(blank=True, help_text='Patient user account this case belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
