# Generated by Django 5.2.9 on 2025-12-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('radiologist', 'Radiologist'), ('researcher', 'Researcher'), ('admin', 'Administrator')], default='doctor', help_text='User role in the system', max_length=20),
        ),
    ]
